[package]
name = "twitter_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
twitter-v2 = "0.1.8"
tokio = { version = "1.43.0", features = ["full"] }
cron = "0.15.0"
chrono = "0.4.39"
llm-chain = "0.13.0"
llm-chain-openai = "0.13.0"
actix-web = "4.9.0"
